[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "skyfield_web"
version = "0.1.0"
dependencies = [
    "flask",
    "skyfield",
    "matplotlib",
    "pytz",
    "flask-limiter",
    "cachelib",
    "astral",
]

[project.scripts]
skyfield_web = "skyfield_web.app:main"



